---
# handlers file for config-zabbix-server
- name: "restart zabbix-server"
  ansible.builtin.service:
    name: zabbix-server 
    state: restarted
    enabled: yes
  become: true

- name: "restart apache2"
  ansible.builtin.service:
    name: apache2 
    state: restarted
    enabled: yes
  become: true