---
# handlers file for filebeat.install
- name: "daemon-reload"
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: filebeat.service
    state: started
- name: "restart-nginx"
  ansible.builtin.service:
    name: nginx
    state: restarted