---
# tasks file for prepearing_server
- name: "install-app"
  ansible.builtin.apt:
    name:
      - nginx
      - zabbix-agent
    state: latest
    update_cache: yes
- name: "set-zabbix-server-ip"
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    insertafter: "Server=127.0.0.1"
    line: "Server=192.168.10.10"
  notify:
    - restart zabbix-agent
- name: "upload site"
  ansible.builtin.copy:
    src: ./file/site/html
    dest: /var/www/
    owner: root
    group: root
    mode: "0755"
  notify:
    - restart nginx