---
# handlers file for prepearing_server
- name: "restart zabbix-agent"
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes

- name: "restart nginx"
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes