---
# tasks file for filebeat.install
- name: "push-filebeat"
  ansible.builtin.copy:
    src: ./file/packej/filebeat-7.14.1-amd64.deb
    dest: /home/ubuntu/
- name: "install-filebeat"
  ansible.builtin.apt:
    deb: /home/ubuntu/filebeat-7.14.1-amd64.deb #Можно мыло бы обойтись и этим модулем но зерколо яндекса нестабильно, иногда эластик пропадает
- name: "push-filebeat-cfg"
  ansible.builtin.copy:
    src: ./file/cfg.file/filebeat.yml
    dest: /etc/filebeat/
    owner: root
    group: root
    mode: 0600
- name: "daemon-reload"
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: filebeat.service
    state: started
- name: "restart-nginx"
  ansible.builtin.service:
    name: nginx
    state: restarted
- name: "modules-enable-nginx"
  ansible.builtin.shell:
    cmd: filebeat modules enable nginx
- name: "filebeat-setup"
  ansible.builtin.shell:
    cmd: sudo filebeat setup #простой became не работает, пришлось писать sudo